name: goreleaser
on: [push, pull_request]
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Setup SSH Keys and known_hosts
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
    - name: goreleaser
      uses: goreleaser/goreleaser-action@master
      with:
        args: release --rm-dist --snapshot
        key: ${{ secrets.SSH_PRIVATE_KEY }}
